import assert from "node:assert/strict";
import test from "node:test";
import { createIsolatedRestoreDatabase, verifyRestoredDatabase } from "../src/backup/restore.ts";

test("isolated restore databases are generated by the recovery tool and force-dropped after verification", async () => {
  const statements: string[] = [];
  const handle = await createIsolatedRestoreDatabase({
    adminDatabaseUrl: "postgresql://restore:secret@postgres:5432/postgres?sslmode=require",
    suffix: "proof_20260804",
    clientFactory: () => ({
      async connect() {},
      async query(text) {
        statements.push(text);
      },
      async end() {},
    }),
  });

  assert.equal(handle.database, "qm_restore_proof_20260804");
  assert.match(handle.databaseUrl, /qm_restore_proof_20260804/);
  assert.match(handle.databaseUrl, /application_name=qm-backup-restore/);
  assert.deepEqual(statements, ['CREATE DATABASE "qm_restore_proof_20260804"']);
  assert.equal(await handle.cleanup(), true);
  assert.equal(await handle.cleanup(), true);
  assert.deepEqual(statements, [
    'CREATE DATABASE "qm_restore_proof_20260804"',
    'DROP DATABASE "qm_restore_proof_20260804" WITH (FORCE)',
  ]);
});

test("isolated restore administration refuses application databases", async () => {
  await assert.rejects(
    createIsolatedRestoreDatabase({
      adminDatabaseUrl: "postgresql://restore:secret@postgres:5432/qm",
      suffix: "unsafe",
    }),
    /maintenance database/,
  );
});

function verificationClient(serverVersion: number, sessionEntryCount: string) {
  return {
    async connect() {},
    async query<T extends Record<string, unknown>>(text: string, _values?: unknown[]) {
      let rows: Array<Record<string, unknown>> = [];
      if (text.includes("server_version_num")) rows = [{ server_version_num: serverVersion }];
      else if (text.includes("information_schema.tables")) {
        rows = [{ table_name: "session_entries" }, { table_name: "sessions" }];
      } else if (text.includes('count(*)::text AS count FROM "session_entries"')) {
        rows = [{ count: sessionEntryCount }];
      } else if (text.includes('count(*)::text AS count FROM "sessions"')) {
        rows = [{ count: "2" }];
      } else if (text.includes('max("updated_at")')) {
        rows = [{ maximum: "1785890000000000" }];
      } else if (text.includes("information_schema.columns")) {
        rows = [{ table_name: "sessions", column_name: "organization_id" }];
      } else if (text.includes('SELECT 1 FROM "sessions"')) {
        rows = [{ exists: 1 }];
      }
      return { rows: rows as T[], rowCount: rows.length };
    },
    async end() {},
  };
}

const expectedDatabaseInvariants = {
  organizationId: "default-org",
  targetPostgresServerVersionNum: 180004,
  minimumTableCount: 2,
  tableRowCountsJson: JSON.stringify({ session_entries: "5", sessions: "2" }),
  tableMaxTimestampsJson: JSON.stringify({ "sessions.updated_at": "1785890000000000" }),
  requiredApplicationTablesJson: JSON.stringify(["sessions", "session_entries"]),
};

test("restore verification proves PostgreSQL server_version_num 180004, exact rows and timestamps, organization, and application tables", async () => {
  const result = await verifyRestoredDatabase({
    databaseUrl: "postgresql://restore:secret@postgres:5432/qm_restore_proof?application_name=qm-backup-restore",
    expected: expectedDatabaseInvariants,
    clientFactory: () => verificationClient(180004, "5"),
  });

  assert.deepEqual(result, {
    postgresServerVersionNum: 180004,
    postgresVersion: true,
    schema: true,
    rowBounds: true,
    timestamps: true,
    organization: true,
    applicationHealth: true,
  });
});

test("restore verification rejects PostgreSQL 17", async () => {
  const result = await verifyRestoredDatabase({
    databaseUrl: "postgresql://restore:secret@postgres:5432/qm_restore_proof?application_name=qm-backup-restore",
    expected: expectedDatabaseInvariants,
    clientFactory: () => verificationClient(170006, "5"),
  });

  assert.equal(result.postgresVersion, false);
  assert.equal(result.postgresServerVersionNum, 170006);
});

test("restore verification rejects a different PostgreSQL 18 minor", async () => {
  const result = await verifyRestoredDatabase({
    databaseUrl: "postgresql://restore:secret@postgres:5432/qm_restore_proof?application_name=qm-backup-restore",
    expected: expectedDatabaseInvariants,
    clientFactory: () => verificationClient(180003, "5"),
  });

  assert.equal(result.postgresVersion, false);
  assert.equal(result.postgresServerVersionNum, 180003);
});

test("restore verification rejects manifest row mismatches", async () => {
  const result = await verifyRestoredDatabase({
    databaseUrl: "postgresql://restore:secret@postgres:5432/qm_restore_proof?application_name=qm-backup-restore",
    expected: expectedDatabaseInvariants,
    clientFactory: () => verificationClient(180004, "4"),
  });

  assert.equal(result.rowBounds, false);
  assert.equal(result.applicationHealth, false);
});
